[build]
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://emp-h6p98jwpk-teamoflifeboxs-projects.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
