import express from 'express';
import studentRoutes from './student/index.js';
import adminRoutes from './admin/index.js';
import coursesRoutes from './courses.js';
import examsRoutes from './exams.js';
import assignmentsRoutes from './assignments.js';
import assignmentSubmissionsRoutes from './assignmentSubmissions.js';
import codingExamsRoutes from './codingExams.js';
import addLectureRoutes from './addLecture.js';
import addClassLink from './addClassLink.js';
import notificationRoutes from './notificationRoutes.js';
import editdeleteRoutes from './editdeleteLecture.js';
import classLinksRoutes from './classLinks.js';
const router = express.Router();
router.use('/student', studentRoutes);
router.use('/admin', adminRoutes);
router.use('/courses', coursesRoutes);
router.use('/exams', examsRoutes);
router.use('/assignments', assignmentsRoutes);
router.use('/assignment-submissions', assignmentSubmissionsRoutes);
router.use('/codingExams', codingExamsRoutes);
router.use("/addLecture",addLectureRoutes);
router.use("/notifications",notificationRoutes);
router.use("/lectures",editdeleteRoutes);
router.use("/addClassLink",addClassLink);
router.use("/classLinks",classLinksRoutes);
export default router;
